In [1]:
from sklearn.datasets import load_iris
import numpy as np
from collections import Counter
import math
from collections import Counter
from numpy import inf
iris = load_iris()
X_ion = np.genfromtxt("ionosphere.txt", delimiter=",")

In [2]:
X_ion = np.genfromtxt("ionosphere.txt", delimiter=",",
    usecols=np.arange(34))

In [3]:
y_ion = np.genfromtxt("ionosphere.txt", delimiter=",",
    usecols=34, dtype='int')

In [4]:
#splitting iris dataset into training and test sets
from sklearn.model_selection import train_test_split
X_iris_train, X_iris_test, y_iris_train, y_iris_test = train_test_split(iris['data'],
iris['target'], random_state=301)

In [5]:
#splitting ionosphere dataset into training and test sets
X_ion_train, X_ion_test, y_ion_train, y_ion_test = train_test_split(X_ion,
y_ion, random_state=301)

In [6]:
def euclideanDistance(x_test_dist, x_train_dist):                          #Computes the Euclidean distance using numpy array
    """
    This functions takes two parameters and calculates the Euclidean Distance between them
    """
    sums = np.sum((x_test_dist-x_train_dist)**2, axis=1)                   #axis 1 means row wise summation
    return np.sqrt(sums)                                                   #square root of the sum of squares to calculate the distance

In [7]:
help(euclideanDistance)

Help on function euclideanDistance in module __main__:

euclideanDistance(x_test_dist, x_train_dist)
    This functions takes two parameters and calculates the Euclidean Distance between them



In [8]:
def kNeighbourNeighboursClassifier(X_train,X_test,y_train,k):               #implementation of k nearest neighbour for all k
    """
    This function takes the number of neighbours for the K nearest neighbours algorithm and calculates the nearest neighbour bases on it.
    """
    y_predicted_label_set = np.array([]).astype(int)                        #predicted label set to be returned for test set
    for x_test_individual in X_test:                                        #looping through each row/sample of test data set
        euc_distance = euclideanDistance(x_test_individual,X_train)         #calling the euclidean distance methos we declared
        shortest_distance = np.argpartition(euc_distance,k)[:k]             #avoids shorting the whole array
        possible_y_label = [y_train[index] for index in shortest_distance]  #set of y_labels
        vote_for_labels = Counter(possible_y_label)                         #using counter collections
        value, count = vote_for_labels.most_common()[0]                     #find most occuring label
        y_predicted_label_set = np.append(y_predicted_label_set, value)     #add to the predicted label set
    return y_predicted_label_set

In [9]:
help(kNeighbourNeighboursClassifier)

Help on function kNeighbourNeighboursClassifier in module __main__:

kNeighbourNeighboursClassifier(X_train, X_test, y_train, k)
    This function takes the number of neighbours for the K nearest neighbours algorithm and calculates the nearest neighbour bases on it.



In [10]:
#prediction for 1NN for iris dataset
y_pred = kNeighbourNeighboursClassifier(X_iris_train,X_iris_test,y_iris_train,1) 
print("Prediction of Test set label:\n", y_pred)
print("Number of errors made: ", sum(y_pred != y_iris_test))
print("Test Error rate: ",sum(y_pred != y_iris_test)/len(y_iris_test))

Prediction of Test set label:
 [2 0 1 2 0 2 2 0 0 1 2 1 0 1 0 0 0 2 2 1 0 1 0 0 0 2 0 2 1 2 0 1 1 1 1 0 1
 2]
Number of errors made:  1
Test Error rate:  0.02631578947368421


In [11]:
#prediction for 3NN for iris dataset
y_pred = kNeighbourNeighboursClassifier(X_iris_train,X_iris_test,y_iris_train,3) 
print("Prediction of Test set label:\n", y_pred)
print("Number of errors made : ", sum(y_pred != y_iris_test))
print("Test Error rate: ",sum(y_pred != y_iris_test)/len(y_iris_test))

Prediction of Test set label:
 [2 0 1 2 0 2 2 0 0 1 2 1 0 1 0 0 0 2 2 1 0 1 0 0 0 2 0 2 1 2 0 1 1 1 1 0 1
 2]
Number of errors made :  1
Test Error rate:  0.02631578947368421


In [12]:
#prediction for 1NN for ionosphere dataset
y_pred = kNeighbourNeighboursClassifier(X_ion_train,X_ion_test,y_ion_train,1) 
print("Prediction of Test set label:\n", y_pred)
print("Number of errors made : ", sum(y_pred != y_ion_test))
print("Test Error rate: ",sum(y_pred != y_ion_test)/len(y_ion_test))

Prediction of Test set label:
 [ 1  1  1 -1  1  1  1  1  1  1  1 -1  1  1 -1  1  1  1  1  1  1  1 -1 -1
 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1 -1 -1
 -1  1  1 -1  1  1  1  1 -1  1 -1 -1  1  1  1  1  1  1  1  1  1 -1 -1  1
  1  1 -1 -1 -1  1  1  1  1 -1  1 -1  1  1  1 -1]
Number of errors made :  8
Test Error rate:  0.09090909090909091


In [13]:
#prediction for 3NN for ionosphere dataset
y_pred = kNeighbourNeighboursClassifier(X_ion_train,X_ion_test,y_ion_train,3) 
print("Prediction of Test set label:\n", y_pred)
print("Number of errors made : ", sum(y_pred != y_ion_test))
print("Test Error rate: ",sum(y_pred != y_ion_test)/len(y_ion_test))

Prediction of Test set label:
 [ 1  1  1 -1  1  1  1  1  1  1  1 -1  1  1 -1  1  1  1  1  1  1  1 -1 -1
 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1 -1
 -1  1  1  1  1  1  1 -1 -1  1 -1 -1  1  1  1  1  1  1  1  1  1 -1 -1  1
  1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1  1  1 -1]
Number of errors made :  10
Test Error rate:  0.11363636363636363


In [20]:
#prediction for 5NN for iris dataset
y_pred = kNeighbourNeighboursClassifier(X_iris_train,X_iris_test,y_iris_train,5) 
print("Prediction of Test set label:\n", y_pred)
print("Number of errors made: ", sum(y_pred != y_iris_test))
print("Test Error rate: ",sum(y_pred != y_iris_test)/len(y_iris_test))

Prediction of Test set label:
 [2 0 1 2 0 2 2 0 0 1 2 1 0 1 0 0 0 2 2 1 0 1 0 0 0 2 0 2 1 2 0 1 1 1 1 0 1
 2]
Number of errors made:  1
Test Error rate:  0.02631578947368421


In [20]:
#prediction for 5NN for iris dataset
y_pred = kNeighbourNeighboursClassifier(X_iris_train,X_iris_test,y_iris_train,5) 
print("Prediction of Test set label:\n", y_pred)
print("Number of errors made: ", sum(y_pred != y_iris_test))
print("Test Error rate: ",sum(y_pred != y_iris_test)/len(y_iris_test))

Prediction of Test set label:
 [2 0 1 2 0 2 2 0 0 1 2 1 0 1 0 0 0 2 2 1 0 1 0 0 0 2 0 2 1 2 0 1 1 1 1 0 1
 2]
Number of errors made:  1
Test Error rate:  0.02631578947368421


In [14]:
def conformalPredictor(X_train,X_test,y_train, label_domain):
    """
    This function computes the p value - conformal prediction for each of the test sample data for all the labels
    """
    p_value_array  = None
    for x_test_individual in X_test:                                                                  #looping through rach test data
        p_value_array_for_all_label = np.zeros(len(label_domain))
        for index_no,n in enumerate(label_domain):                                                    #looping through each distinct label
            X_train_with_test = np.vstack((X_train,x_test_individual))                                #adding test data to training data and creating new sample 
            y_train_with_test = np.append(y_train,n)
            distances = np.zeros(len(X_train_with_test))  
            #count = 0
            for index, a in enumerate(X_train_with_test):  
                indexes_with_same_label =(y_train_with_test == y_train_with_test[index]).nonzero() [0]
                indexes_with_same_label = indexes_with_same_label[indexes_with_same_label != index]
                distances_same = np.linalg.norm(X_train_with_test[indexes_with_same_label]-a,axis=1)   #calcutating same distance
                min_distance_same = np.min(distances_same)                                             #getting minimum
                indexes_with_diff_label =(y_train_with_test != y_train_with_test[index]).nonzero() [0] 
                #indexes_with_diff_label = indexes_with_diff_label[indexes_with_diff_label != index]
                distances_diff = np.linalg.norm(X_train_with_test[indexes_with_diff_label]-a,axis=1)  #calcutation different distance
                min_distance_diff = np.min(distances_diff)                                            #getting minimum
                if min_distance_same == 0 :                                                           #handling 0/0 cases - start
                    if min_distance_diff != 0:
                        distances[index] = inf
                    else:
                        distances[index] = 0    
                else:
                    distances[index] = min_distance_diff/min_distance_same                            #handling 0/0 cases - end
            rank = len(distances) - sum(distances>distances[-1])                                      #calculating rank for one label
            p_value = rank/len(distances)                                                             #getting p value for one label
            p_value_array_for_all_label[index_no] = p_value                                           #merging p values for all labels for one dataset
        if p_value_array is None:
            p_value_array = p_value_array_for_all_label
        else:
            p_value_array = np.vstack((p_value_array,p_value_array_for_all_label))
    return(p_value_array)                                                                             #returning p values for all test datasets

In [15]:
#calculating p value for iris dataset
y_iris_p_values = conformalPredictor(X_iris_train,X_iris_test,y_iris_train, [ i for i in range(0, len(iris.target_names))])
y_hat = np.argmax(y_iris_p_values,axis=1)
print("P values for iris dataset: \n",y_iris_p_values)
print("\nAccuracy of the model for iris dataset: ",np.mean(y_hat==y_iris_test))

P values for iris dataset: 
 [[0.00884956 0.00884956 0.55752212]
 [0.88495575 0.00884956 0.00884956]
 [0.00884956 0.51327434 0.00884956]
 [0.00884956 0.03539823 0.07079646]
 [0.88495575 0.00884956 0.00884956]
 [0.00884956 0.01769912 0.15044248]
 [0.00884956 0.00884956 0.66371681]
 [0.69026549 0.00884956 0.00884956]
 [0.92920354 0.00884956 0.00884956]
 [0.00884956 0.30973451 0.00884956]
 [0.00884956 0.00884956 0.52212389]
 [0.00884956 0.07079646 0.03539823]
 [0.7699115  0.00884956 0.00884956]
 [0.00884956 0.77876106 0.00884956]
 [0.96460177 0.00884956 0.00884956]
 [0.77876106 0.00884956 0.00884956]
 [0.66371681 0.00884956 0.00884956]
 [0.00884956 0.00884956 0.51327434]
 [0.00884956 0.04424779 0.07079646]
 [0.00884956 0.3539823  0.00884956]
 [0.77876106 0.00884956 0.00884956]
 [0.00884956 0.46017699 0.00884956]
 [0.85840708 0.00884956 0.00884956]
 [0.79646018 0.00884956 0.00884956]
 [0.67256637 0.00884956 0.00884956]
 [0.00884956 0.00884956 0.52212389]
 [0.95575221 0.00884956 0.00884956]

In [16]:
#calculating p values for ionosphere dataset
y_ion_p_values = conformalPredictor(X_ion_train,X_ion_test,y_ion_train, [-1, 1])
print("P values for ionosphere dataset: \n",y_ion_p_values)
y_hat = np.argmax(y_ion_p_values,axis=1)
print("\nAccuracy of the model for ionosphere dataset: ",np.mean(y_hat==y_ion_test))

P values for ionosphere dataset: 
 [[0.00378788 0.86742424]
 [0.00378788 0.90151515]
 [0.00378788 0.95833333]
 [0.28787879 0.08712121]
 [0.00378788 0.79545455]
 [0.00757576 0.48863636]
 [0.00378788 0.76136364]
 [0.08712121 0.27272727]
 [0.00378788 0.74621212]
 [0.00378788 0.74242424]
 [0.00378788 0.76893939]
 [0.33712121 0.05681818]
 [0.03409091 0.39393939]
 [0.00757576 0.48106061]
 [0.41287879 0.03409091]
 [0.00378788 0.95454545]
 [0.00757576 0.48106061]
 [0.01136364 0.48863636]
 [0.00378788 0.93560606]
 [0.13636364 0.17424242]
 [0.00378788 0.75378788]
 [0.00378788 0.66666667]
 [0.33333333 0.05681818]
 [0.16666667 0.14772727]
 [0.1969697  0.12878788]
 [0.29166667 0.08712121]
 [0.00757576 0.625     ]
 [0.00757576 0.52651515]
 [0.00378788 0.76136364]
 [0.00378788 0.68939394]
 [0.00378788 0.94318182]
 [0.00757576 0.62121212]
 [0.02651515 0.43181818]
 [0.00378788 0.88257576]
 [0.00757576 0.59469697]
 [0.00757576 0.63636364]
 [0.00378788 0.84090909]
 [0.00378788 0.73484848]
 [0.00378788 0.

In [17]:
#function to calculate average false p value for the given datset
def averageFalseP(y_test,y_p_values):
    avg_false_p_value = 0
    total_sum_rowwise = 0
    num_rows, num_cols = y_p_values.shape
    for index_label,n in enumerate(y_test):                           #looping over each test data label
        for index_p_value,m in enumerate(y_p_values):                 #looping over each row of p value data array
            if index_label == index_p_value:                          #comparing indexed for y_
                sum = 0
                for index, o in enumerate(y_p_values[index_p_value]): #looping over each row value for p value array
                    if n != index:                                    #eliminating true label
                        sum = sum+o
                avg_rowwise = sum/(num_cols-1)
                total_sum_rowwise = total_sum_rowwise + avg_rowwise   #getting total false p values sum
    avg_false_p_value = total_sum_rowwise/(y_p_values.size-num_rows)
    return(avg_false_p_value)                                         #returning average false p value 

In [18]:
#calculating average false p value for iris dataset
average_false_p_vale_iris = averageFalseP(y_iris_test,y_iris_p_values)
print("Average false p value for iris dataset: ",average_false_p_vale_iris)
y_hat = np.argmax(y_iris_p_values,axis=1)
print("Accuracy: ",np.mean(y_hat==y_iris_test))

Average false p value for iris dataset:  0.005298090358639967
Accuracy:  0.9736842105263158


In [19]:
#calculating average false p value for ionosphere dataset
average_false_p_vale_ion = averageFalseP(y_ion_test,y_ion_p_values)
print("Average false p value for ionosphere dataset: ",average_false_p_vale_ion)
y_hat = np.argmax(y_ion_p_values,axis=1)
print("Accuracy: ",np.mean(y_hat==y_ion_test))

Average false p value for ionosphere dataset:  0.14445592286501385
Accuracy:  0.6590909090909091


In [20]:
#prediction for 5NN for iris dataset
y_pred = kNeighbourNeighboursClassifier(X_iris_train,X_iris_test,y_iris_train,5) 
print("Prediction of Test set label:\n", y_pred)
print("Number of errors made: ", sum(y_pred != y_iris_test))
print("Test Error rate: ",sum(y_pred != y_iris_test)/len(y_iris_test))

Prediction of Test set label:
 [2 0 1 2 0 2 2 0 0 1 2 1 0 1 0 0 0 2 2 1 0 1 0 0 0 2 0 2 1 2 0 1 1 1 1 0 1
 2]
Number of errors made:  1
Test Error rate:  0.02631578947368421
